[MySQL]
username = "user"
passwordEnvKey = "passwordEnvKey"
host = "localhost"
port = 3306
databaseName = "crawler"
connection = "tcp"

[Redis]
host = "localhost"
port = 6379
connection = "tcp"

[Http]
proxyUrl = ""

[[webSites]]
domain = "example.com"
startPage = "http://example.com/"
allowedDomain = "example.com$"
crawlerNum = 10

[[webSites]]
domain = "golang.org"
startPage = "https://golang.org/"
allowedDomain = "golang.org$"
crawlerNum = 10
